_target_: models.dit.dit.DiT
input_size: 32
patch_size: 4
in_channels: 4
time_channels: 2
hidden_size: 768
depth: 12
num_heads: 12
mlp_ratio: 4.0
num_classes: 1000
learn_sigma: false
class_dropout_prob: 0.1
use_separate_time_embeds: true
