_target_: models.dit.dit.DiT
input_size: 32
patch_size: 2
in_channels: 4
time_channels: 2
hidden_size: 384
depth: 12
num_heads: 6
mlp_ratio: 4.0
num_classes: 1000
learn_sigma: false
class_dropout_prob: 0.1
